import { editor } from 'monaco-editor';

export const draculaTheme: editor.IStandaloneThemeData = {
    base: 'vs-dark',
    inherit: true,
    rules: [
        { token: 'comment', foreground: '6272a4', fontStyle: 'italic' },
        { token: 'string', foreground: 'f1fa8c' },
        { token: 'number', foreground: 'bd93f9' },
        { token: 'keyword', foreground: 'ff79c6' },
        { token: 'operator', foreground: 'ff79c6' },
        { token: 'function', foreground: '50fa7b' },
        { token: 'variable', foreground: 'f8f8f2' },
        { token: 'type', foreground: '8be9fd' },
        { token: 'class', foreground: '8be9fd' },
        { token: 'constant', foreground: 'bd93f9' },
        { token: 'delimiter', foreground: 'f8f8f2' },
        { token: 'identifier', foreground: 'f8f8f2' },
        { token: 'annotation', foreground: '50fa7b' },
        { token: 'decorator', foreground: '50fa7b' },
        { token: 'regexp', foreground: 'f1fa8c' },
        { token: 'invalid', foreground: 'ff5555', fontStyle: 'bold' },
    ],
    colors: {
        'editor.background': '#282a36',
        'editor.foreground': '#f8f8f2',
        'editor.lineHighlightBackground': '#44475a',
        'editorLineNumber.foreground': '#6272a4',
        'editorLineNumber.activeForeground': '#f8f8f2',
        'editor.selectionBackground': '#44475a',
        'editor.inactiveSelectionBackground': '#44475a80',
        'editorCursor.foreground': '#f8f8f2',
        'editorWhitespace.foreground': '#6272a440',
        'editorIndentGuide.background': '#6272a440',
        'editorIndentGuide.activeBackground': '#6272a4',
        'editorWidget.background': '#282a36',
        'editorWidget.border': '#6272a4',
        'editorSuggestWidget.background': '#282a36',
        'editorSuggestWidget.border': '#6272a4',
        'editorSuggestWidget.selectedBackground': '#44475a',
        'editorHoverWidget.background': '#282a36',
        'editorHoverWidget.border': '#6272a4',
        'scrollbarSlider.background': '#44475a80',
        'scrollbarSlider.hoverBackground': '#44475aCC',
        'scrollbarSlider.activeBackground': '#44475aFF',
        'minimapSlider.background': '#44475a80',
        'minimapSlider.hoverBackground': '#44475aCC',
        'minimapSlider.activeBackground': '#44475aFF',
    }
};
